import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createApp} from '../src/server.mjs';
import {dateMinute} from '../src/time.mjs';
const require=createRequire(import.meta.url);let pw;try{pw=require('playwright');}catch{pw=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const models={config:()=>({deepseekKey:'test'}),usage:()=>({spent:0,limit:200,rows:[]}),complete:async(m,o)=>({text:o.json?JSON.stringify({action:'create',reason:'想写一小段音乐故事',idea:'机械少女与琴键'}):'她把还没弹完的旋律记在纸上，等下一次接着写。'})};
const app=await createApp({dbPath:':memory:',background:false,models,clock:()=>dateMinute('2026-09-20','10:00')});const initial=app.service.state();initial.agency.creationEnabled=true;app.store.save(initial);await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
let browser;try{browser=await pw.chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+app.server.address().port);await page.locator('nav [data-tab="persona"]').click();await page.locator('#miku-agency').waitFor();await page.locator('#agency-run').click();await page.waitForFunction(()=>document.querySelector('#agency-artifacts').textContent.includes('旋律'));await page.locator('#web-life details').first().locator('summary').click();await page.locator('#web-life-add [name="title"]').fill('知乎测试');await page.locator('#web-life-add [name="url"]').fill('https://www.zhihu.com/question/123/answer/456');await page.locator('#web-life-add button').click();await page.waitForFunction(()=>document.querySelector('#web-life-sources').textContent.includes('知乎测试'));await page.locator('#web-life-toggle').click();await page.waitForFunction(()=>document.querySelector('#web-life-toggle').textContent.includes('恢复'));assert.equal(app.service.state().webLife.enabled,false);await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('#miku-agency').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2));assert.deepEqual(errors,[]);mkdirSync('test-output',{recursive:true});await page.screenshot({path:resolve('test-output/agency-mobile.png'),fullPage:true});console.log('Isolated browser verified: create, source form, pause, mobile width, no page errors; no network/model calls.');}finally{await browser?.close();await app.close();}
