import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.mjs';
import {Service} from '../src/service.mjs';
import {Chat} from '../src/chat.mjs';
import {Agency} from '../src/agency.mjs';
import {Models} from '../src/models.mjs';
import {Scheduler} from '../src/reminders.mjs';
import {dateMinute} from '../src/time.mjs';
function fixture(action='create'){
  let now=dateMinute('2026-09-19','10:00'),calls=0;const store=new Store(':memory:',now),service=new Service(store,()=>now);
  const models={config:()=>({deepseekKey:'test'}),complete:async(msg,opt)=>{calls++;return {text:(opt.json && !['dialogue','initiative-share','initiative-reminder','work-log'].includes(opt.purpose))?JSON.stringify({action,reason:'想完成一个自己的小作品。',idea:'月亮与电子琴',topicId:'math'}):'她把最后一个音符留给了窗外的月亮。'};}};
  const initial=service.state();initial.agency.creationEnabled=true;initial.agency.shareCheckLimit=2;store.save(initial);
  const chat=new Chat(service,models),learning={running:false,run:async()=>({message:'没有读到资料。'})},agency=new Agency(service,chat,models,learning);
  return {store,service,models,chat,learning,agency,get calls(){return calls;},advance:m=>now+=m};
}
test('actual creation is persisted, original text preserved, cooldown and daily caps survive clearing',async()=>{const f=fixture();try{await f.agency.run();let a=f.service.state().agency;assert.equal(a.runs[0].status,'done');assert.equal(a.artifacts[0].text,'她把最后一个音符留给了窗外的月亮。');assert.ok(a.needs.creation<.2);await f.agency.run();assert.equal(f.calls,2);f.advance(240);await f.agency.run();f.advance(240);await f.agency.run();f.service.command('agency.clear');f.advance(240);await f.agency.run();assert.equal(f.calls,6);assert.equal(f.service.state().agency.artifacts.length,0);}finally{f.store.close();}});
test('silence is a valid decision and failed study cannot satisfy curiosity',async()=>{for(const action of ['rest','learn']){const f=fixture(action);try{const before=f.service.state().agency.needs.curiosity;await f.agency.run();const a=f.service.state().agency;assert.equal(a.runs[0].status,action==='rest'?'rest':'failed');assert.equal(a.needs.curiosity,before);assert.equal(f.store.messages().length,0);}finally{f.store.close();}}});
test('pause during model request cancels output and forget removes derived context',async()=>{const f=fixture();try{let resolve,started;const ready=new Promise(r=>started=r);f.models.complete=()=>{started();return new Promise(r=>resolve=r);};const run=f.agency.run();await ready;f.service.command('agency.settings',{enabled:false});resolve({text:JSON.stringify({action:'create',reason:'想写作'})});await run;assert.equal(f.service.state().agency.artifacts.length,0);assert.equal(f.service.state().agency.runs[0].status,'cancelled');f.service.command('memory.add',{content:'临时资料'});f.service.command('memory.remove',{id:f.store.read().memories[0].id});assert.equal(f.service.state().agency.runs[0].reason,undefined);}finally{f.store.close();}});
test('interrupted attempt is recovered without replay and simultaneous wakes call once',async()=>{const f=fixture();try{const a=f.service.state();a.agency.runs=[{id:'interrupted',at:dateMinute('2026-09-19','09:00'),status:'running'}];a.agency.lastAt=a.agency.runs[0].at;f.store.save(a);new Agency(f.service,f.chat,f.models,f.learning);assert.equal(f.service.state().agency.runs[0].status,'interrupted');await f.agency.run();assert.equal(f.calls,0);f.advance(240);await Promise.all([f.agency.run(),f.agency.run()]);assert.equal(f.calls,2);}finally{f.store.close();}});
test('sharing needs a real artifact, is queued once, and pause cancels delivery',async()=>{const f=fixture('share');try{const s=f.service.state();s.agency.artifacts.push({id:'story',kind:'fiction',text:'月亮与电子琴'});f.store.save(s);f.store.addChat('user','你好',f.service.clock()-180);await f.agency.run();assert.equal(f.service.state().agency.runs[0].status,'queued');assert.equal(f.store.messages().length,3);assert.equal(f.agency.canShare(f.service.state()),false);f.service.command('agency.settings',{enabled:false});await new Scheduler(f.service).deliver();assert.ok(f.store.messages().every(x=>x.status==='cancelled'));}finally{f.store.close();}});
test('initiative budget blocks before network while ordinary dialogue remains usable',async()=>{const f=fixture();try{const s=f.service.state();s.agency.monthlyLimit=.001;f.store.save(s);let calls=0;const models=new Models(f.store,()=>({deepseekKey:'test',deepseekModel:'deepseek-v4-pro',monthlyLimit:200}),{clock:f.service.clock,fetcher:async()=>{calls++;return new Response(JSON.stringify({choices:[{message:{content:'好'}}],usage:{prompt_tokens:10,completion_tokens:10}}));}});await assert.rejects(models.complete([],{purpose:'initiative-decision',maxOutput:500}),/自主活动预算/);assert.equal(calls,0);await models.complete([],{purpose:'dialogue',maxOutput:500});assert.equal(calls,1);}finally{f.store.close();}});
test('completed work can be shared after ten minutes without waiting four hours',async()=>{const f=fixture();try{f.store.addChat('user','你好',f.service.clock()-180);await f.agency.run();const activityAt=f.service.state().agency.lastAt;assert.equal(f.agency.shareDue(),false);f.advance(10);assert.equal(f.agency.due(),false);assert.equal(f.agency.shareDue(),true);f.models.complete=async(m,o)=>({text:(o.json && !['dialogue','initiative-share','initiative-reminder','work-log'].includes(o.purpose))?JSON.stringify({action:'share',reason:'想分享刚写的作品'}):'我写了个小片段，想给你看看。'});await f.agency.tick();assert.equal(f.service.state().agency.lastAt,activityAt);assert.equal(f.service.state().agency.runs.at(-1).mode,'share');assert.equal(f.service.state().agency.runs.at(-1).status,'queued');assert.ok(f.service.state().agency.artifacts[0].sharedAt);}finally{f.store.close();}});
test('choosing silence has independent hourly and daily limits that survive clearing',async()=>{const f=fixture('rest');try{const s=f.service.state();s.agency.lastAt=f.service.clock();s.agency.artifacts=[{id:'piece',at:f.service.clock()-15,text:'原创片段'}];f.store.save(s);f.store.addChat('user','你好',f.service.clock()-180);await f.agency.tick();await f.agency.tick();assert.equal(f.calls,1);f.advance(60);await f.agency.tick();assert.equal(f.calls,2);f.service.command('agency.clear');const next=f.service.state();next.agency.artifacts=[{id:'new',at:f.service.clock()-15,text:'另一片段'}];f.store.save(next);f.advance(60);assert.equal(f.agency.shareDue(),false);assert.equal(f.calls,2);}finally{f.store.close();}});
test('local proactive delivery appears in chat once while WeChat remains pending, then records real channel acceptance',async()=>{const f=fixture('share');try{const s=f.service.state();s.agency.artifacts=[{id:'piece',at:f.service.clock()-15,text:'原创片段'}];f.store.save(s);f.store.addChat('user','你好',f.service.clock()-180);await f.agency.runShare();let ready=false,sends=0;const scheduler=new Scheduler(f.service,{weixinReady:()=>ready,sendWeixin:async()=>{sends++;return 'remote-test-id';}});await scheduler.deliver();await scheduler.deliver();assert.equal(f.store.chats().filter(x=>x.role==='assistant').length,1);assert.equal(sends,0);assert.equal(f.service.state().agency.runs.at(-1).deliveries.weixin,undefined);assert.match(f.service.state().agency.runs.at(-1).result,/电脑聊天/);ready=true;await scheduler.deliver();assert.equal(sends,1);assert.equal(f.service.state().agency.runs.at(-1).deliveries.weixin.status,'sent');assert.equal(f.store.chats().filter(x=>x.role==='assistant').length,1);}finally{f.store.close();}});
test('separate sharing never overrides quiet hours or recent conversation',()=>{const f=fixture();try{const s=f.service.state();s.agency.artifacts=[{id:'piece',at:f.service.clock()-15,text:'原创片段'}];f.store.save(s);f.store.addChat('user','你好',f.service.clock());assert.equal(f.agency.shareDue(),false);assert.match(f.agency.shareStatus().reason,/刚聊过/);f.advance(780);assert.equal(f.agency.shareDue(),false);assert.match(f.agency.shareStatus().reason,/免打扰/);}finally{f.store.close();}});

test('authorized website work remains available at night without personal message candidates',async()=>{
  const f=fixture('site_work');
  try{
    f.advance(900);let executions=0,options=[];
    f.agency.work={due:()=>true,snapshot:()=>({actions:['maintain'],reportable:true}),thinking(){},considered(){},run:async()=>{executions++;return {message:'真实维护结果'};}};
    f.models.complete=async(messages)=>{options=JSON.parse(messages.at(-1).content).candidates;return {text:JSON.stringify({action:'site_work',reason:'处理服务器任务'})};};
    assert.equal(f.agency.due(),true);assert.equal(f.agency.shareDue(),false);
    await f.agency.run();assert.deepEqual(options,['rest','site_work']);assert.equal(executions,1);assert.equal(f.store.messages().length,0);
    f.service.command('agency.settings',{enabled:false});assert.equal(f.agency.due(),false);
  }finally{f.store.close();}
});
