import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,sep} from 'node:path';
import {Store} from '../src/store.mjs';
import {Service} from '../src/service.mjs';
import {plan} from '../src/planner.mjs';
import {dateMinute,dateKey,overlap} from '../src/time.mjs';
import {decay,expression,recordEvent} from '../src/persona.mjs';
import {Models,BudgetError} from '../src/models.mjs';
import {Chat} from '../src/chat.mjs';
import {Scheduler,isQuiet} from '../src/reminders.mjs';
const monday=dateMinute('2026-09-14','07:00');
function fixture(at=monday,path=':memory:'){let now=at;const store=new Store(path,now),service=new Service(store,()=>now);return {store,service,setTime(t){now=t;},close(){store.close();}};}
function removeTestDirectory(dir){assert.ok(realpathSync(dir).startsWith(realpathSync(tmpdir())+sep+'miku-test-'));rmSync(dir,{recursive:true,force:true});}
function task(service,args={}){service.command('task.add',{title:'高数作业',remaining:120,deadline:'2026-09-16 23:59',...args});return service.store.read().tasks.at(-1);}
function verify(s,now){const p=s.plan;const rows=p.allocations;
  for(const b of rows){assert.ok(b.start>=now);assert.ok(b.end>b.start);const t=s.tasks.find(t=>t.id===b.taskId);assert.ok(b.end<=t.deadline);assert.ok(!p.fixed.some(f=>overlap(f,b)),JSON.stringify(b));}
  for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++)assert.ok(!overlap(rows[i],rows[j]),'task overlap');
  for(const t of s.tasks.filter(t=>t.status==='open'))assert.equal(rows.filter(b=>b.taskId===t.id).reduce((n,b)=>n+b.end-b.start,0)+(p.unscheduled.find(u=>u.taskId===t.id)?.minutes||0),t.remaining,'work conservation');
}
test('strict calendar rejects impossible dates and ambiguous clocks',()=>{assert.throws(()=>dateMinute('2026-02-30'));assert.throws(()=>dateMinute('2026-09-14','24:00'));});
test('split work respects fixed courses, meals and travel',()=>{const f=fixture();try{f.service.command('course.save',{title:'高数',weekday:1,start:'08:00',end:'09:40',travelBefore:15,travelAfter:10});task(f.service);verify(f.store.read(),monday);}finally{f.close();}});
test('odd/even weeks and one occurrence cancellation',()=>{const f=fixture();try{f.service.command('course.save',{title:'单双周',weekday:1,start:'10:00',end:'11:00',weekFrom:1,weekTo:6,parity:'even',travelBefore:0,travelAfter:0});let s=f.store.read();assert.equal(s.plan.fixed.filter(b=>b.kind==='course').length,1);const c=s.courses[0];assert.equal(dateKey(s.plan.fixed.find(b=>b.kind==='course').start),'2026-09-14');f.service.command('course.cancelDate',{id:c.id,date:'2026-09-14'});assert.equal(f.store.read().plan.fixed.filter(b=>b.kind==='course').length,0);}finally{f.close();}});
test('remaining time is replaced, not added; independent plans retain valid slots',async()=>{const f=fixture();try{const t=task(f.service);const other=task(f.service,{title:'英语',remaining:60,deadline:'2026-09-17 22:00'});const before=f.store.read().plan.allocations.filter(b=>b.taskId===other.id);const chat=new Chat(f.service,{config:()=>({deepseekKey:''})});await chat.run('高数还需要两小时');assert.equal(f.store.read().tasks.find(x=>x.id===t.id).remaining,120);assert.deepEqual(f.store.read().plan.allocations.filter(b=>b.taskId===other.id),before);verify(f.store.read(),monday);}finally{f.close();}});
test('rest moves all future flexible work, retains fixed appointments and deadlines',()=>{const f=fixture();try{task(f.service);f.service.command('block.add',{title:'聚餐',start:'2026-09-14 19:00',end:'2026-09-14 20:00'});const deadline=f.store.read().tasks[0].deadline;f.service.command('rest');const s=f.store.read();assert.ok(s.plan.allocations.every(b=>dateKey(b.start)!=='2026-09-14'));assert.equal(s.tasks[0].deadline,deadline);assert.ok(s.plan.fixed.some(b=>b.title==='聚餐'));verify(s,monday);}finally{f.close();}});
test('infeasible and overdue tasks report deficit without changing deadlines',()=>{const f=fixture();try{task(f.service,{remaining:1000,deadline:'2026-09-14 08:00'});assert.ok(f.store.read().plan.unscheduled[0].minutes>900);task(f.service,{title:'过期',deadline:'2026-09-13 12:00'});assert.match(f.store.read().plan.unscheduled.find(x=>x.title==='过期').reason,/已过/);verify(f.store.read(),monday);}finally{f.close();}});
test('repeated commands are idempotent and mismatched reuse is rejected',()=>{const f=fixture();try{const a={title:'test',remaining:60,deadline:'2026-09-15 12:00'};f.service.command('task.add',a,'same');f.service.command('task.add',a,'same');assert.equal(f.store.read().tasks.length,1);assert.throws(()=>f.service.command('task.add',{...a,remaining:90},'same'));}finally{f.close();}});
test('completion does not reward intimacy or automatically progress relationship',()=>{const f=fixture();try{const t=task(f.service),before=f.store.read().persona.relationship;f.service.command('task.complete',{id:t.id});f.service.command('task.complete',{id:t.id});const p=f.store.read().persona;assert.deepEqual(p.relationship,before);assert.equal(p.stage,'new');assert.equal(p.events.filter(e=>e.kind==='completed').length,1);}finally{f.close();}});
test('transactions roll back earlier model actions when a later action is invalid',async()=>{const f=fixture();try{const fake={config:()=>({deepseekKey:'test'}),complete:async()=>({text:JSON.stringify({actions:[{action:'task.add',args:{title:'不能留下',remaining:60,deadline:'2026-09-16 10:00'}},{action:'persona.address',args:{address:''}}]})})};const c=new Chat(f.service,fake);await assert.rejects(c.run('测试两条操作'));assert.equal(f.store.read().tasks.length,0);}finally{f.close();}});
test('restart retains memory, conflict and decayed emotion',()=>{const dir=mkdtempSync(join(tmpdir(),'miku-test-'));let f=fixture(monday,join(dir,'db.sqlite'));try{f.service.command('memory.add',{content:'喜欢安静'});const s=f.store.read();recordEvent(s.persona,'conflict','真实冲突测试',monday,'conflict1');f.store.save(s);f.close();f=fixture(monday+1440,join(dir,'db.sqlite'));const state=f.service.state();assert.equal(state.memories[0].content,'喜欢安静');assert.equal(state.persona.conflicts.length,1);assert.ok(state.persona.emotions.annoyed<.2&&state.persona.emotions.annoyed>0);}finally{f.close();removeTestDirectory(dir);}});
test('forget purges chat, derived summaries, proposals, events and old commands',()=>{const f=fixture();try{f.service.command('memory.add',{content:'secret-saffron'});const s=f.store.read();s.summaries.push({text:'secret-saffron'});s.episodes.push({body:'secret-saffron'});f.store.save(s);f.store.addChat('user','secret-saffron',monday);f.service.command('memory.remove',{id:s.memories[0].id});assert.ok(!JSON.stringify(f.service.state()).includes('secret-saffron'));assert.ok(!JSON.stringify(f.store.history()).includes('secret-saffron'));assert.ok(!JSON.stringify(f.store.db.prepare('SELECT * FROM commands').all()).includes('secret-saffron'));}finally{f.close();}});
test('budget reserves in-flight use, enforces cap and counts reasoning output',async()=>{const f=fixture();try{let calls=0;const config=()=>({deepseekKey:'x',deepseekModel:'deepseek-flash',monthlyLimit:.01,usdCny:7});const m=new Models(f.store,config,{clock:()=>monday,fetcher:async()=>{calls++;return new Response(JSON.stringify({usage:{prompt_tokens:500,completion_tokens:1000},choices:[{message:{content:'ok'},finish_reason:'stop'}]}));}});await assert.rejects(m.complete([{role:'user',content:'hello'}]),BudgetError);assert.equal(calls,0);const affordable=new Models(f.store,()=>({...config(),monthlyLimit:1}),{clock:()=>monday,fetcher:m.fetcher});await affordable.complete([{role:'user',content:'hello'}],{maxOutput:1500});assert.equal(affordable.usage().spent,.009);assert.equal(calls,1);}finally{f.close();}});
test('disabled OpenAI never makes a request',async()=>{const f=fixture();try{const m=new Models(f.store,()=>({openaiKey:'x',openaiEnabled:false}),{fetcher:()=>{throw new Error('must not call');}});await assert.rejects(m.complete([],{provider:'openai'}),/尚未启用/);}finally{f.close();}});
test('quiet hours defer notifications; expired items are never sent',async()=>{const f=fixture(dateMinute('2026-09-14','23:00'));try{let calls=0;f.store.enqueue('feishu:quiet',f.service.clock(),f.service.clock()+600,{text:'a'},'feishu');f.store.enqueue('feishu:expired',f.service.clock()-60,f.service.clock()-1,{text:'b'},'feishu');const scheduler=new Scheduler(f.service,{feishuReady:()=>true,sendFeishu:async()=>{calls++;}});await scheduler.deliver();assert.equal(calls,0);assert.equal(f.store.db.prepare("SELECT status FROM outbox WHERE id='feishu:expired'").get().status,'expired');f.setTime(dateMinute('2026-09-15','07:10'));await scheduler.deliver();assert.equal(calls,1);}finally{f.close();}});
test('recovery merges overdue notifications, repeated delivery is deduplicated',async()=>{const f=fixture(dateMinute('2026-09-14','11:00'));try{let calls=0;for(let i=0;i<4;i++)f.store.enqueue('feishu:old'+i,f.service.clock()-90,f.service.clock()+60,{text:'old'},'feishu');const scheduler=new Scheduler(f.service,{feishuReady:()=>true,sendFeishu:async p=>{calls++;return 'remote';}});await scheduler.deliver();await scheduler.deliver();assert.equal(calls,1);assert.equal(f.store.db.prepare("SELECT COUNT(*) AS n FROM outbox WHERE status='superseded'").get().n,4);const delivered=f.store.messages().find(r=>r.payload.kind==='digest');assert.equal(delivered.status,'sent');assert.equal(delivered.payload.text,'系统提醒：old');}finally{f.close();}});
test('cancelled tasks invalidate pending notifications',()=>{const f=fixture();try{const t=task(f.service);assert.ok(f.store.messages().some(n=>n.status==='pending'&&n.payload.taskId===t.id));f.service.command('task.cancel',{id:t.id});assert.ok(!f.store.messages().some(n=>n.status==='pending'&&n.payload.taskId===t.id));}finally{f.close();}});
test('failed sender retries later with the same deduplication key',async()=>{const f=fixture(dateMinute('2026-09-14','10:00'));try{const keys=[];f.store.enqueue('feishu:reply:test',f.service.clock(),f.service.clock()+60,{kind:'reply',text:'test'},'feishu');const scheduler=new Scheduler(f.service,{feishuReady:()=>true,sendFeishu:async(p,k)=>{keys.push(k);if(keys.length===1)throw new Error('offline');return'remote';}});await scheduler.deliver();f.setTime(f.service.clock()+2);await scheduler.deliver();assert.deepEqual(keys,['feishu:reply:test','feishu:reply:test']);}finally{f.close();}});
test('random scheduling scenarios conserve work and avoid collisions',()=>{let seed=93;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};for(let round=0;round<30;round++){const f=fixture();try{for(let n=0;n<12;n++)task(f.service,{title:`task ${n}`,remaining:15+Math.floor(rand()*200),minBlock:5+Math.floor(rand()*30),priority:1+Math.floor(rand()*3),deadline:monday+60+Math.floor(rand()*7*1440),splittable:rand()>.2});verify(f.store.read(),monday);}finally{f.close();}}});
