import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,sep} from 'node:path';
import {Store} from '../src/store.mjs';
import {Service} from '../src/service.mjs';
import {Chat} from '../src/chat.mjs';
import {Models} from '../src/models.mjs';
import {dateMinute,overlap} from '../src/time.mjs';
const at=dateMinute('2026-09-14','10:00');
function fixture(){let now=at;const store=new Store(':memory:',now),service=new Service(store,()=>now);return {store,service,setTime:t=>now=t,close:()=>store.close()};}
const config={deepseekKey:'test-only',deepseekModel:'deepseek-flash',openaiEnabled:true,openaiKey:'test-only',openaiModel:'gpt-6-astra',monthlyLimit:200,usdCny:7.5};
test('forget removes content while keeping deduplication receipts',async()=>{const f=fixture();try{const args={title:'真实任务',remaining:60,deadline:'2026-09-16 22:00'};f.service.command('task.add',args,'old-task');const chat=new Chat(f.service,{config:()=>({deepseekKey:''})});await chat.run('今天不想学了',{requestId:'old-chat'});f.service.command('memory.add',{content:'private-amber'});const m=f.store.read().memories[0];f.service.command('memory.remove',{id:m.id});f.service.command('task.add',args,'old-task');const revision=f.store.read().revision;await chat.run('今天不想学了',{requestId:'old-chat'});assert.equal(f.store.read().revision,revision);assert.equal(f.store.read().tasks.length,1);for(const table of ['commands','inbox','outbox'])assert.ok(!JSON.stringify(f.store.db.prepare('SELECT * FROM '+table).all()).includes('private-amber'));}finally{f.close();}});
test('SSE survives byte splits, hides reasoning, and accounts usage exactly once',async()=>{const f=fixture();try{let request;const payload=[{choices:[{delta:{reasoning_content:'private reasoning'}}]},{choices:[{delta:{content:'你好，'}}]},{choices:[{delta:{content:'我是 Miku。'},finish_reason:'stop'}]},{choices:[],usage:{prompt_tokens:1000,prompt_cache_hit_tokens:500,completion_tokens:200}}].map(d=>'data: '+JSON.stringify(d)+'\r\n\r\n').join('')+'data: [DONE]\n\n';
  const bytes=Buffer.from(payload);const m=new Models(f.store,()=>config,{clock:()=>at,fetcher:async(url,opt)=>{request=JSON.parse(opt.body);return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.subarray(i,i+7));c.close();}}));}});let visible='';const r=await m.complete([{role:'user',content:'你好'}],{stream:true,onDelta:t=>visible+=t,maxOutput:1000});assert.equal(r.text,'你好，我是 Miku。');assert.equal(visible,r.text);assert.equal(request.stream_options.include_usage,true);assert.equal(m.usage().rows.length,1);assert.equal(m.usage().spent,.00262);
}finally{f.close();}});
test('advisor and DeepSeek writer share current facts without changing the role',async()=>{const f=fixture();try{f.service.command('memory.add',{content:'喜欢电子音乐',source:'用户记录'});f.service.command('task.add',{title:'高数',remaining:120,deadline:'2026-09-16 22:00'});const s=f.store.read();s.persona.stage='close';f.store.save(s);const prompts=[];const m={config:()=>config,complete:async(msgs,opts)=>{prompts.push({msgs,opts});return {text:(opts.json && !['dialogue','initiative-share','initiative-reminder','work-log'].includes(opts.purpose))?JSON.stringify({actions:[],advisor:'advice'}):'这些安排我记得。'};}};const c=new Chat(f.service,m);await c.run('你好',{requestId:'one'});await c.run('深入想想',{requestId:'two',deep:true});assert.deepEqual(prompts.map(p=>p.opts.provider),['deepseek','openai','deepseek','deepseek','openai','deepseek']);for(const p of prompts){assert.ok(JSON.stringify(p.msgs).includes('喜欢电子音乐'));assert.ok(JSON.stringify(p.msgs).includes('close'));assert.ok(JSON.stringify(p.msgs).includes('高数'));}assert.equal(f.store.read().persona.stage,'close');}finally{f.close();}});
test('invalid extraction may escalate once before any state mutation',async()=>{const f=fixture();try{let calls=0;const m={config:()=>config,complete:async(msgs,opts)=>{calls++;if(calls===1)return{text:'invalid JSON'};assert.equal(opts.provider,calls===2?'openai':'deepseek');return{text:(opts.json && !['dialogue','initiative-share','initiative-reminder','work-log'].includes(opts.purpose))?'{"actions":[]}':'已核对。'};}};const r=await new Chat(f.service,m).run('检查安排');assert.equal(r.provider,'deepseek');assert.match(r.warning,/重新检查/);assert.equal(calls,4);assert.equal(f.store.read().tasks.length,0);}finally{f.close();}});
test('duplicate chat IDs neither replay mutations nor accept changed text',async()=>{const f=fixture();try{const chat=new Chat(f.service,{config:()=>({deepseekKey:''})});const r=await chat.run('今天不想学了',{requestId:'duplicate'});const revision=f.store.read().revision;assert.deepEqual(await chat.run('今天不想学了',{requestId:'duplicate'}),r);assert.equal(f.store.read().revision,revision);await assert.rejects(chat.run('重新安排',{requestId:'duplicate'}),/编号冲突/);}finally{f.close();}});
test('confirmation via chat commits a pending fixed change exactly once',async()=>{const f=fixture();try{const p=f.service.command('proposal.create',{kind:'action',payload:{action:'block.add',args:{title:'会议',start:'2026-09-15 10:00',end:'2026-09-15 11:00'}}}).proposal;assert.equal(f.store.read().blocks.length,0);const chat=new Chat(f.service,{config:()=>({deepseekKey:''})});await chat.run('确认',{requestId:'yes'});await chat.run('确认',{requestId:'yes'});assert.equal(f.store.read().blocks.length,1);assert.equal(f.store.read().proposals.length,0);assert.throws(()=>f.service.command('proposal.confirm',{id:'different'},'yes:action:0'),/不同操作/);}finally{f.close();}});
test('rest undo restores a feasible plan and refuses after new progress',()=>{const f=fixture();try{f.service.command('task.add',{title:'高数',remaining:120,deadline:'2026-09-16 22:00'});const original=f.store.read().plan.allocations;f.service.command('rest');f.service.command('plan.undo');assert.deepEqual(f.store.read().plan.allocations,original);f.service.command('rest');f.service.command('task.progress',{id:f.store.read().tasks[0].id,minutes:30});assert.throws(()=>f.service.command('plan.undo'),/不符合|状态变化/);assert.equal(f.store.read().tasks[0].remaining,90);}finally{f.close();}});
test('current time blocks are reserved before scheduling a newly urgent task',()=>{const f=fixture();try{f.service.command('task.add',{title:'已有工作',remaining:120,deadline:'2026-09-17 22:00'});const first=f.store.read().plan.allocations[0];f.setTime(first.start+20);f.service.command('task.add',{title:'紧急新增',remaining:45,deadline:'2026-09-14 14:00'});const s=f.store.read(),rows=s.plan.allocations;assert.ok(rows.some(b=>b.ongoing&&b.taskId===first.taskId));for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++)assert.ok(!overlap(rows[i],rows[j]));for(const t of s.tasks){const future=rows.filter(b=>b.taskId===t.id).reduce((n,b)=>n+b.end-Math.max(b.start,f.service.clock()),0);assert.equal(future+(s.plan.unscheduled.find(u=>u.taskId===t.id)?.minutes||0),t.remaining);}assert.equal(s.tasks[0].remaining,120);}finally{f.close();}});
function tinyPdf(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 100] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const stream='BT /F1 12 Tf 10 50 Td (Monday 08:00 Math) Tj ET';objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);let doc='%PDF-1.4\n';const offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(doc));doc+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(doc);doc+=`xref\n0 6\n0000000000 65535 f \n`+offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(doc);}
test('PDF and image imports produce reviewable drafts without creating courses',async()=>{const {importTimetable}=await import('../src/importer.mjs');const {createCanvas}=await import('@napi-rs/canvas');const f=fixture();try{let calls=0;const m={complete:async msgs=>{calls++;const image=msgs[1].content[1].image_url.url;assert.ok(image.startsWith('data:image/png;base64,'));assert.ok(image.length>100);return {text:JSON.stringify({courses:[{title:'高数',weekday:1,start:'08:00',end:'09:40',parity:'odd'}],notes:'核对周次'})};}};const draft=await importTimetable(tinyPdf(),'application/pdf',m);f.service.command('draft.add',draft);assert.equal(f.store.read().courses.length,0);const d=f.store.read().drafts[0];f.service.command('draft.confirm',{id:d.id});assert.equal(f.store.read().courses.length,1);assert.equal(f.store.read().courses[0].parity,'odd');await importTimetable(createCanvas(50,50).toBuffer('image/png'),'image/png',m);assert.equal(calls,2);await assert.rejects(importTimetable(Buffer.from('bad'),'application/pdf',m),/有效/);}finally{f.close();}});
test('Feishu only accepts bound private text; duplicates and restart replies are safe',async()=>{const dir=mkdtempSync(join(tmpdir(),'miku-test-feishu-'));process.env.MIKU_CONFIG=join(dir,'config.json');const {saveConfig}=await import('../src/config.mjs');const {Feishu}=await import('../src/feishu.mjs');const f=fixture();try{saveConfig({feishuUser:'allowed',feishuEnabled:true});const chat=new Chat(f.service,{config:()=>({deepseekKey:''})}),fs=new Feishu(f.service,chat);const event=(uid,id,content,chat_type='p2p')=>({sender:{sender_id:{open_id:uid}},message:{message_id:id,chat_type,message_type:'text',content:JSON.stringify({text:content})}});fs.receive(event('stranger','a','今天不想学了'));fs.receive(event('allowed','b','今天不想学了','group'));assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM inbox').get().n,0);fs.receive(event('allowed','c','今天不想学了'));fs.receive(event('allowed','c','今天不想学了'));await fs.processInbox();const rev=f.store.read().revision;await fs.processInbox();assert.equal(f.store.read().revision,rev);assert.equal(f.store.messages().filter(m=>m.id==='feishu:reply:feishu:c').length,1);
  // Simulate a crash after the chat commits but before its reply is enqueued.
  await chat.run('重新安排',{requestId:'feishu:crash',source:'feishu'});await fs.processInbox();assert.ok(f.store.messages().some(m=>m.id==='feishu:reply:feishu:crash'));const denied=fs.card({operator:{open_id:'stranger'},action:{value:{action:'complete',taskId:'x'}}});assert.equal(denied.toast.type,'error');
}finally{f.close();assert.ok(realpathSync(dir).startsWith(realpathSync(tmpdir())+sep+'miku-test-feishu-'));rmSync(dir,{recursive:true,force:true});}});

