import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.mjs';
import {Service} from '../src/service.mjs';
import {Chat} from '../src/chat.mjs';
import {WebLife} from '../src/web-life.mjs';
import {Agency} from '../src/agency.mjs';
import {Scheduler} from '../src/reminders.mjs';
import {dateMinute} from '../src/time.mjs';
const url='https://www.quantamagazine.org/test/';
const body='公开资料描述了测量误差如何影响反馈控制，以及滤波方法对实际观测结果的影响。文章还讨论了如何结合实验确定采样周期，不能仅凭理论推断所有实际系统的表现。';
function fixture(){let now=dateMinute('2026-09-20','09:00');const store=new Store(':memory:',now),service=new Service(store,()=>now),calls=[];let routing={actions:[],act:'question',advisor:'none'};
 const models={config:()=>({deepseekKey:'test',openaiEnabled:false}),complete:async(m,o)=>{calls.push({m,o});if(o.purpose==='routing')return {text:JSON.stringify(routing)};if(o.purpose==='initiative-web-daily')return {text:JSON.stringify({sourceId:'quanta'})};if(o.purpose==='initiative-web-select')return {text:'{"index":0}'};if(o.purpose==='initiative-web-note')return {text:JSON.stringify({note:'测量误差影响控制。',evidence:'测量误差如何影响反馈控制',question:'',essay:'今天读到测量误差的影响，想把这点记下来。'+url,commentObservation:''})};if(o.purpose==='initiative-web-check')return {text:'{"supported":true}'};if(o.purpose==='initiative-decision')return {text:'{"action":"share_web","reason":"想分享这篇阅读日记"}'};return {text:'模型原文，不替换。'};}};
 const chat=new Chat(service,models),web=new WebLife(service,models,{reader:{discover:async()=>[{title:'控制',url,text:body}],document:async()=>({title:'控制',url,text:body,readLevel:'page-text'})}});chat.webLife=web;chat.runtimeInfo=()=>({connected:true,enabled:true,weixinReady:true});return {store,service,models,calls,chat,web,route:r=>routing=r,advance:m=>now+=m};}
test('capability questions see real tools even in social replies; no research keyword fallback',async()=>{const f=fixture();try{f.route({actions:[],act:'social',advisor:'none'});const r=await f.chat.run('你能上网搜索吗，也能主动给我消息吗');assert.equal(r.text,'模型原文，不替换。');assert.equal(f.calls.length,2);const writer=f.calls.at(-1).m.map(x=>x.content).join();assert.match(writer,/"connected":true/);assert.match(writer,/"weixinReady":true/);assert.equal(r.warning,'');}finally{f.store.close();}});
test('chat invokes the real reading workflow without OpenAI and repeated messages do not read again',async()=>{const f=fixture();try{f.route({actions:[],act:'question',advisor:'research',webRequest:{sourceId:'quanta',evidence:'读一篇Quanta'}});const r=await f.chat.run('读一篇Quanta',{requestId:'read'});assert.equal(r.webResult.status,'read');assert.equal(f.service.state().webLife.notes.length,1);assert.equal(r.advisor,'not_needed');assert.match(JSON.stringify(f.calls.at(-1).m),/测量误差如何影响反馈控制/);const count=f.calls.length;await f.chat.run('读一篇Quanta',{requestId:'read'});assert.equal(f.calls.length,count);}finally{f.store.close();}});
test('invalid or quoted tool evidence cannot request arbitrary sources',async()=>{const f=fixture();try{assert.equal((await f.chat.readWeb({sourceId:'quanta',evidence:'查一下'},'你好')).status,'rejected');assert.equal((await f.chat.readWeb({sourceId:'https://127.0.0.1',evidence:'查一下'},'查一下')).status,'unavailable');assert.equal(f.calls.length,0);}finally{f.store.close();}});
test('daily reading and diary delivery complete without any new incoming message',async()=>{const f=fixture();try{f.store.addChat('user','昨天的聊天',f.service.clock()-1440);assert.equal(f.web.dailyDue(),true);await f.chat.exclusive(()=>f.web.daily());assert.equal(f.web.dailyDue(),false);f.advance(10);const agency=new Agency(f.service,f.chat,f.models,{running:false},f.web);let sent;const scheduler=new Scheduler(f.service,{weixinReady:()=>true,sendWeixin:async p=>{sent=p.text;return 'accepted';}});await agency.tick();await scheduler.tick();f.advance(10);await scheduler.tick();assert.equal(sent,'模型原文，不替换。');assert.equal(f.service.state().webLife.notes[0].essay,undefined);assert.equal(f.store.chats().filter(c=>c.role==='user').length,1);assert.equal(f.store.messages().find(r=>r.channel==='weixin'&&r.payload.kind==='proactive').status,'sent');assert.equal(f.service.state().agency.creationEnabled,false);}finally{f.store.close();}});
test('daily selector errors reserve a persistent attempt before calling the model and respect quiet hours',async()=>{const f=fixture();try{f.models.complete=async()=>{throw new Error('network down');};await assert.rejects(f.web.daily(),/network/);assert.equal(f.web.dailyDue(),false);const again=new WebLife(f.service,f.models);assert.equal(again.dailyDue(),false);f.advance(60);assert.equal(again.dailyDue(),true);f.advance(14*60);assert.equal(again.dailyDue(),false);}finally{f.store.close();}});
test('paused creation cannot be reenabled by model choice; old songs never qualify for sharing',async()=>{const f=fixture();try{const s=f.service.state();s.agency.artifacts=[{id:'old',kind:'music-sketch',at:f.service.clock()-20,text:'旧音乐草稿'}];f.store.save(s);f.store.addChat('user','你好',f.service.clock()-180);f.models.complete=async()=>({text:'{"action":"create","format":"music","reason":"想写歌"}'});const a=new Agency(f.service,f.chat,f.models,{running:false});assert.equal(f.service.state().agency.creationEnabled,false);await a.run();assert.equal(f.service.state().agency.runs.at(-1).status,'failed');assert.equal(f.service.state().agency.artifacts.length,1);}finally{f.store.close();}});


