import test from 'node:test';
import assert from 'node:assert/strict';
import {SocialReader} from '../src/social-reader.mjs';
import {WebLife} from '../src/web-life.mjs';
import {Store} from '../src/store.mjs';
import {Service} from '../src/service.mjs';
import {Agency} from '../src/agency.mjs';
import {Chat} from '../src/chat.mjs';
import {webUrl} from '../src/web-life-state.mjs';
import {dateMinute} from '../src/time.mjs';
import {parseFeed} from '../src/public-reader.mjs';
const json=x=>({status:200,text:JSON.stringify(x)});
test('Nature RDF content:encoded is a real feed body with dc:date',()=>{const rows=parseFeed('<rdf:RDF><item><title>Research note</title><link>https://www.nature.com/articles/example</link><content:encoded><![CDATA[<p>A published research note with enough real descriptive content to read.</p>]]></content:encoded><dc:date>2026-09-20</dc:date></item></rdf:RDF>','https://www.nature.com/nature.rss');assert.equal(rows.length,1);assert.equal(rows[0].published,'2026-09-20');assert.match(rows[0].text,/research note/);});
test('Nico discovery uses official bounded snapshot results rather than obsolete RSS',async()=>{let requested;const reader=new SocialReader({read:async url=>{requested=new URL(url);return json({meta:{status:200},data:[{contentId:'sm12345',title:'原创曲',description:'公开介绍',startTime:'2026-09-20'},{contentId:'https://evil.test/',title:'不允许的链接'}]});}});const rows=await reader.discover({kind:'niconico-search',query:'VOCALOID'});assert.equal(requested.hostname,'snapshot.search.nicovideo.jp');assert.equal(requested.searchParams.get('_limit'),'8');assert.equal(rows.length,1);assert.equal(rows[0].url,'https://www.nicovideo.jp/watch/sm12345');});
test('Bilibili distinguishes descriptions, comments and real subtitles, without claiming AI summaries',async()=>{const urls=[],reader=new SocialReader({read:async url=>{urls.push(url);if(url.includes('/view?'))return json({code:0,data:{title:'机器人',desc:'视频介绍',aid:123,cid:456}});if(url.includes('/reply?'))return json({code:0,data:{replies:[{content:{message:'我觉得这个实验的对照还不够'}}]}});if(url.includes('/player/'))return json({code:0,data:{subtitle:{subtitles:[{lan:'zh-CN',subtitle_url:'https://i0.hdslb.com/subtitle/test.json'}]}}});return json({body:[{content:'字幕里实际描述了机器人如何通过编码器测量角度。'}]});}});const d=await reader.document('https://www.bilibili.com/video/BV1xx411c7mD');assert.equal(d.readLevel,'video-subtitles');assert.equal(d.comments.length,1);assert.match(d.text,/编码器/);assert.ok(d.limitations.some(x=>x.includes('AI 总结需登录')));assert.equal(urls.length,4);});
test('refused comments are a limitation, not a fabricated empty consensus or video content',async()=>{const reader=new SocialReader({read:async url=>url.includes('/view?')?json({code:0,data:{title:'介绍',desc:'仅有介绍',aid:123,cid:456}}):json({code:-101})});const d=await reader.document('https://www.bilibili.com/video/BV1xx411c7mD');assert.equal(d.readLevel,'video-description');assert.equal(d.comments.length,0);assert.ok(d.limitations.some(x=>x.includes('未读到评论')));assert.ok(d.limitations.some(x=>x.includes('未读到字幕')));});
test('Nico uses guest metadata and bounded anonymous danmaku without treating them as transcript',async()=>{const requests=[],reader=new SocialReader({read:async(url,opts)=>{requests.push({url,opts});return url.includes('/v3_guest/')?json({meta:{status:200},data:{video:{title:'音乐',description:'创作者的公开介绍'},comment:{nvComment:{server:'https://public.nvcomment.nicovideo.jp',params:{targets:[]},threadKey:'public-ephemeral'}}}}):json({meta:{status:200},data:{threads:[{comments:Array.from({length:50},()=>({body:'很好听'}))}]}});}});const d=await reader.document('https://www.nicovideo.jp/watch/sm12345');assert.equal(d.comments.length,20);assert.equal(d.readLevel,'video-description');assert.equal(requests[1].opts.method,'POST');assert.ok(!JSON.stringify(d).includes('threadKey'));});
test('Nico refuses arbitrary comment server and excluded sites never enter the browse catalog',async()=>{let calls=0;const reader=new SocialReader({read:async()=>{calls++;return json({meta:{status:200},data:{video:{title:'a',description:'b'},comment:{nvComment:{server:'https://evil.example'}}}});}});const d=await reader.document('https://www.nicovideo.jp/watch/sm12345');assert.equal(calls,1);assert.match(d.limitations.at(-1),/不符合预期/);for(const u of ['https://www.douyin.com/video/1','https://www.kuaishou.com/','https://bilibili.com.evil.test/','https://127.0.0.1/'])assert.throws(()=>webUrl(u));});
function fixture({bad=false,reader}={}){const now=dateMinute('2026-09-20','10:00'),store=new Store(':memory:',now),service=new Service(store,()=>now);let calls=0;const url='https://www.quantamagazine.org/example/',text='这篇公开资料讨论了机器人如何通过编码器测量角度，以及测量误差对反馈控制的影响。文中也提到了噪声和采样周期的作用，需要结合具体实验理解。';const note={note:'资料讨论编码器测角及误差。',evidence:bad?'这个句子不在真实材料中':'机器人如何通过编码器测量角度',question:'噪声较大时如何选择滤波方法？',essay:'我读到编码器误差会影响反馈控制，想进一步弄明白滤波方法。来源：'+url,commentObservation:''};const models={config:()=>({deepseekKey:'test'}),complete:async(m,o)=>{calls++;return{text:JSON.stringify(o.purpose==='initiative-web-check'?{supported:true}:note)};}};const web=new WebLife(service,models,{reader:reader||{document:async()=>({url,title:'机器人',text,readLevel:'page-text',comments:[],limitations:[]})}});service.command('web.source',{title:'测试来源',url});return {store,service,web,models,note,sourceId:service.state().webLife.sources.at(-1).id,get calls(){return calls;}};}
test('real evidence gates reusable notes; once daily per source; source quotes and uncertainty persist',async()=>{const f=fixture();try{const r=await f.web.run({sourceId:f.sourceId});assert.equal(r.note.note,f.note.note);assert.equal(r.note.essay,undefined);assert.equal(r.note.question,f.note.question);assert.equal(f.calls,2);await f.web.run({sourceId:f.sourceId});assert.equal(f.calls,2);assert.equal(f.service.state().webLife.notes.length,1);}finally{f.store.close();}});
test('invented evidence is rejected before review or storage',async()=>{const f=fixture({bad:true});try{await f.web.run({sourceId:f.sourceId});assert.equal(f.calls,1);assert.equal(f.service.state().webLife.notes.length,0);assert.equal(f.service.state().webLife.attempts[0].status,'failed');}finally{f.store.close();}});
test('same body from a second source reuses verified notes without extra model requests',async()=>{const f=fixture();try{await f.web.run({sourceId:f.sourceId});f.service.command('web.source',{title:'另一入口',url:'https://www.quantamagazine.org/another/'});const sourceId=f.service.state().webLife.sources.at(-1).id;const result=await f.web.run({sourceId});assert.equal(result.cached,true);assert.equal(f.calls,2);assert.equal(f.service.state().webLife.notes.length,1);}finally{f.store.close();}});
test('model output cannot override tool-owned source, identity or delivery state',async()=>{const f=fixture();try{const complete=f.models.complete;f.models.complete=async(m,o)=>{const r=await complete(m,o);if(o.purpose==='initiative-web-note')r.text=JSON.stringify({...JSON.parse(r.text),id:'invented',url:'https://evil.test/',readLevel:'watched-full-video',sharedAt:123});return r;};const result=await f.web.run({sourceId:f.sourceId});assert.notEqual(result.note.id,'invented');assert.equal(result.note.readLevel,'page-text');assert.equal(result.note.url,'https://www.quantamagazine.org/example/');assert.equal(result.note.sharedAt,undefined);}finally{f.store.close();}});
test('pausing during read prevents later paid calls and forget purges derived notes',async()=>{let resolve,started;const ready=new Promise(r=>started=r);const f=fixture({reader:{document:()=>{started();return new Promise(r=>resolve=r);}}});try{const work=f.web.run({sourceId:f.sourceId});await ready;f.service.command('web.settings',{enabled:false});resolve({title:'旧资料',text:'旧资料'.repeat(40),url:'https://www.quantamagazine.org/example/'});await work;assert.equal(f.calls,0);assert.equal(f.service.state().webLife.notes.length,0);f.service.command('memory.add',{content:'临时记忆'});f.service.command('memory.remove',{id:f.store.read().memories[0].id});assert.equal(f.service.state().webLife.attempts[0].result,undefined);}finally{f.store.close();}});
test('agency shares through the same writer instead of sending a stored essay',async()=>{const f=fixture();try{const chat=new Chat(f.service,f.models),agency=new Agency(f.service,chat,f.models,{running:false},f.web);await f.web.run({sourceId:f.sourceId});f.store.addChat('user','你好',f.service.clock()-180);f.models.complete=async(m,o)=>({text:o.purpose==='initiative-decision'?JSON.stringify({action:'share_web',reason:'读到值得聊的知识'}):'这次结合聊天重新说。'});await agency.run();const row=f.store.db.prepare("SELECT payload FROM outbox WHERE channel='local'").get();assert.equal(JSON.parse(row.payload).text,'这次结合聊天重新说。');assert.ok(f.service.state().webLife.notes[0].sharedAt);assert.equal(agency.canShare(f.service.state()),false);}finally{f.store.close();}});
test('autonomous browse chooses an available tool and satisfies interest only after a verified note',async()=>{const f=fixture();try{const complete=f.models.complete;f.models.complete=async(m,o)=>o.purpose==='initiative-decision'?{text:JSON.stringify({action:'browse',sourceId:f.sourceId,reason:'想弄明白角度测量'})}:complete(m,o);const a=new Agency(f.service,new Chat(f.service,f.models),f.models,{running:false},f.web),before=f.service.state().agency.needs.curiosity;await a.run();assert.equal(f.service.state().agency.runs[0].action,'browse');assert.equal(f.service.state().agency.runs[0].status,'done');assert.ok(f.service.state().agency.needs.curiosity<before);assert.equal(f.service.state().webLife.notes.length,1);}finally{f.store.close();}});
test('explicit legacy creation saves an original text sketch without claiming audio',async()=>{const f=fixture();try{const initial=f.service.state();initial.agency.creationEnabled=true;f.store.save(initial);f.models.complete=async(m,o)=>({text:(o.json && !['dialogue','initiative-share','initiative-reminder','work-log'].includes(o.purpose))?JSON.stringify({action:'create',format:'music',idea:'清晨的旋律',reason:'想试一段自己的音乐'}):'原创草稿：Cmaj7—Am7—Fmaj7—G，92 BPM，电钢琴开头，副歌加弦乐。'});const a=new Agency(f.service,new Chat(f.service,f.models),f.models,{running:false});await a.run();const saved=f.service.state().agency.artifacts[0];assert.equal(saved.kind,'music-sketch');assert.match(saved.text,/92 BPM/);assert.match(f.service.state().agency.runs[0].result,/尚未生成音频/);}finally{f.store.close();}});

