import {createHash,randomUUID} from 'node:crypto';
export function failureKind(message){if(/robots|抓取规则|非公网|不允许|授权|权限|本次用户消息/.test(message))return 'policy';if(/验证码|安全验证|登录/.test(message))return 'verification';if(/HTTP (400|401|403|412|429)|未开放/.test(message))return 'access';if(/格式|正文|无效|空|完整/.test(message))return 'invalid_result';return 'transient';}
export class CapabilityMemory{
 constructor(service){this.service=service;this.db=service.store.db;this.db.exec('CREATE TABLE IF NOT EXISTS capability_runs(id TEXT PRIMARY KEY,capability TEXT,implementation TEXT,scope TEXT,target TEXT,ok INTEGER,kind TEXT,latency INTEGER,at INTEGER,version TEXT); CREATE INDEX IF NOT EXISTS capability_scope ON capability_runs(capability,scope,at); CREATE TABLE IF NOT EXISTS tool_lessons(id TEXT PRIMARY KEY,tool TEXT,lesson TEXT UNIQUE,at INTEGER)');}
 record({capability,implementation,scope,target='',ok,error='',latency=0,version='1'}){this.db.prepare('INSERT INTO capability_runs VALUES(?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),capability,implementation,scope,createHash('sha256').update(target).digest('hex'),ok?1:0,ok?'success':failureKind(error),Math.max(0,Math.round(latency)),this.service.clock(),version);this.db.exec('DELETE FROM capability_runs WHERE id NOT IN (SELECT id FROM capability_runs ORDER BY at DESC,rowid DESC LIMIT 400)');}
 history(capability,scope){return this.db.prepare('SELECT * FROM capability_runs WHERE capability=? AND scope=? ORDER BY at DESC,rowid DESC LIMIT 40').all(capability,scope);}
 order(capability,scope,implementations){const rows=this.history(capability,scope),now=this.service.clock();return [...implementations].sort((a,b)=>{const rank=id=>{const recent=rows.filter(r=>r.implementation===id&&r.version==='1'&&now-r.at<7*1440),last=recent[0];if(!last)return 0;if(!last.ok&&now-last.at<60)return -10;const successes=recent.filter(r=>r.ok).length;return successes/(recent.length+1);};return rank(b)-rank(a);});}
 blocked(capability,scope){const rows=this.history(capability,scope),last=rows[0];return !!last&&last.kind==='policy'&&this.service.clock()-last.at<60;}
 view(){const rows=this.db.prepare('SELECT * FROM capability_runs ORDER BY at DESC,rowid DESC LIMIT 400').all(),groups=new Map();for(const row of rows){const key=[row.capability,row.implementation,row.scope].join('|');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}return [...groups.values()].map(a=>({capability:a[0].capability,implementation:a[0].implementation,scope:a[0].scope,version:a[0].version,attempts:a.length,successes:a.filter(r=>r.ok).length,successRate:a.filter(r=>r.ok).length/a.length,lastVerified:a.find(r=>r.ok)?.at||null,lastFailure:a.find(r=>!r.ok)?.kind||null,latencyMs:Math.round(a.reduce((n,r)=>n+r.latency,0)/a.length),status:a[0].ok?'observed-working':'needs-review',quality:'仅验证返回结构；不等于科学结论正确',cost:'模型费用统一计入原有账本'}));}
 context(){return this.view().slice(0,8);}
 // Usage lessons the agent wrote for itself after real runs (ExpeL-style insights); bounded and purged with memory.
 addLesson({tool,lesson}){this.db.prepare('INSERT OR IGNORE INTO tool_lessons VALUES(?,?,?,?)').run(randomUUID(),tool,lesson,this.service.clock());this.db.exec('DELETE FROM tool_lessons WHERE id NOT IN (SELECT id FROM tool_lessons ORDER BY at DESC,rowid DESC LIMIT 40)');}
 lessons(limit=12){return this.db.prepare('SELECT tool,lesson,at FROM tool_lessons ORDER BY at DESC,rowid DESC LIMIT ?').all(limit);}
 resetAccess(){this.db.prepare("DELETE FROM capability_runs WHERE ok=0 AND kind IN ('verification','access')").run();}
}
