import { initShell } from '../js/shell.js';
import { hubApi,hubState,loginURL } from '../js/hub.js';
import { esc } from '../js/data.js';
import '../styles/products.css';
initShell();const $=s=>document.querySelector(s),S={boards:[],items:[],lane:'recommended',board:'',cursor:null,serial:0,thread:null,user:null};
const campusName={all:'全校',shahe:'沙河',xueyuanlu:'学院路'};
function boards(){ $('#circle-boards').innerHTML=[{id:'',name:'全部话题',description:'看看校园里正在发生什么'},...S.boards].map((b,i)=>`<button data-board-id="${esc(b.id)}" aria-pressed="${S.board===b.id}"><span class="forum-icon" style="--forum-h:${20+i*43}">${['☷','◉','✦','⌘','↗','∑','▤'][i]||'#'}</span><span><b>${esc(b.name)}</b><small>${esc(b.description)}</small></span></button>`).join('');$('#post-board').innerHTML=S.boards.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');}
function card(p){const d=p.data;return `<article class="circle-post"><div class="post-author"><span class="author-avatar">${esc((p.owner?.name||'同学').slice(0,1))}</span><span><b>${esc(p.owner?.name||'同学')}</b><small>${esc(campusName[d.circle?.campus]||'全校')} · ${esc(S.boards.find(b=>b.id===d.circle?.board)?.name||'校园话题')}</small></span><span class="post-date">${esc((d.circle?.publishedAt||p.created||'').slice(0,10))}</span></div><button class="post-open" data-post="${esc(p.id)}"><h2>${esc(d.title)}</h2><p>${esc(d.body||d.summary||'')}</p></button>${p.photos?.length?`<div class="post-photos">${p.photos.slice(0,3).map(src=>`<img src="${esc(src)}" loading="lazy" alt="投稿照片">`).join('')}</div>`:''}${p.selection?`<p class="post-selection">编辑精选 · ${esc(p.selection.reason)}</p>`:''}<div class="post-footer"><button data-like="${esc(p.id)}" aria-pressed="${p.liked}">${p.liked?'♥':'♡'} ${p.likes||0}</button><button data-post="${esc(p.id)}">评论 ${p.replies||0}</button><button data-star="${esc(p.id)}">${p.starred?'★ 已收藏':'☆ 收藏'}</button></div></article>`;}
async function load(more=false){const serial=++S.serial;$('#circle-status').textContent='正在加载…';try{const r=await hubApi.circleFeed({lane:S.lane,board:S.board,campus:$('#circle-campus').value,q:$('#circle-q').value.trim(),cursor:more?S.cursor:null});if(serial!==S.serial)return;S.cursor=r.nextCursor;S.items=more?[...S.items,...r.items]:r.items;$('#circle-feed').innerHTML=S.items.map(card).join('')||'<div class="product-empty"><span class="empty-symbol">✦</span><h2>第一条好讨论，从你开始。</h2><p>这里还没有公开帖子。分享一个真实经历，或发起一次合作。</p><button class="btn btn-primary" data-compose>发布第一条</button></div>';$('#circle-more').hidden=!S.cursor;$('#circle-status').textContent=S.lane==='recommended'?'根据主动选择的兴趣和编辑核对推荐，可切换“最新”。':'';}catch(e){if(serial!==S.serial)return;$('#circle-status').innerHTML=`${esc(e.message)} <button class="btn-link" data-retry>重试</button>`;}}
async function compose(){const s=await hubState();if(!s.user){location.href=loginURL();return;}$('#circle-editor').showModal();$('#post-board').value=S.board||S.boards[0]?.id||'';$('#circle-form').elements.campus.value=$('#circle-campus').value;}
async function thread(id){const r=await hubApi.entry(id);S.thread=id;const d=r.data||{};$('#thread-body').innerHTML=`<p class="section-label">${esc(r.owner?.name||'同学')} · ${esc(campusName[d.circle?.campus]||'全校')}</p><h2>${esc(d.title)}</h2><div class="thread-text">${esc(d.body)}</div>${d.circle?.external?.url?`<a href="${esc(d.circle.external.url)}" target="_blank" rel="noopener">阅读原文 ↗</a>`:''}<h3>讨论</h3>${(r.replies||[]).map(x=>`<div class="thread-reply"><b>${esc(x.author?.name||x.owner?.name||'同学')}</b><p>${esc(x.body)}</p>${x.state!=='published'?'<small>待审核 · 仅作者与维护者可见</small>':''}</div>`).join('')||'<p class="small-note">暂无公开回复。</p>'}`;$('#reply-status').textContent='';if(!$('#circle-thread').open)$('#circle-thread').showModal();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.hasAttribute('data-board-id')){S.board=b.dataset.boardId;boards();await load();}if(b.hasAttribute('data-lane')){S.lane=b.dataset.lane;$('#circle-lanes').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));await load();}if(b.hasAttribute('data-post'))await thread(b.dataset.post);if(b.hasAttribute('data-compose'))await compose();if(b.hasAttribute('data-retry'))await load();if(b.hasAttribute('data-like')||b.hasAttribute('data-star')){b.disabled=true;const p=S.items.find(x=>x.id===(b.dataset.like||b.dataset.star));if(b.hasAttribute('data-like')){const r=await hubApi.likeCirclePost(p.id,!p.liked);Object.assign(p,r);}else{await hubApi.star(p.id,!p.starred);p.starred=!p.starred;}$('#circle-feed').innerHTML=S.items.map(card).join('');}}catch(err){$('#circle-status').textContent=err.message;}finally{b.disabled=false;}});
$('#circle-compose').onclick=compose;$('#circle-more').onclick=()=>load(true);$('#circle-campus').onchange=()=>load();let timer;$('#circle-q').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>load(),200);};
$('#circle-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type=submit]'),v=Object.fromEntries(new FormData(f)),photos=[...f.elements.photos.files];if(photos.length>9){$('#post-status').textContent='最多上传 9 张照片。';return;}b.disabled=true;try{const uploads=[];for(const file of photos){$('#post-status').textContent=`正在上传 ${file.name}`;uploads.push((await hubApi.upload(file)).id);}const r=await hubApi.createCirclePost({title:v.title,body:v.body,tags:v.tags.split(/[，,、\s]+/).filter(Boolean).slice(0,10),uploads,rightsConfirmed:f.elements.rights.checked,circle:{format:'thread',board:v.board,campus:v.campus,visibility:'public'}});await hubApi.submit(r.id,r.editRevision);$('#post-status').innerHTML='已提交审核。<a href="me.html#entries">查看投稿进度 →</a>';f.reset();}catch(err){$('#post-status').textContent=err.message;}finally{b.disabled=false;}};
$('#thread-reply').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{const result=await hubApi.reply(S.thread,f.elements.body.value);f.reset();await thread(S.thread);$('#reply-status').textContent=result.state==='published'?'回复已发布。':'回复已提交，审核后公开。';}catch(err){$('#reply-status').textContent=err.message;}finally{b.disabled=false;}};
async function init(){const s=await hubState();S.user=s.user;const r=await hubApi.circleBoards();S.boards=r.items;boards();await load();const params=new URLSearchParams(location.search);if(params.has('compose'))compose();if(params.get('post'))await thread(params.get('post'));}
init().catch(e=>{$('#circle-status').textContent=e.message;$('#circle-feed').innerHTML='<div class="product-empty"><h2>社区服务暂未连接。</h2><p>论坛需要在线账号与审核服务。已发布的项目仍可在开源广场浏览。</p><a href="discover.html">去开源广场 →</a></div>';});
