import { initShell } from '../js/shell.js';
import { hubApi,hubState,loginURL } from '../js/hub.js';
import { esc } from '../js/data.js';
import '../styles/product-forms.css';
import '../styles/circle-news.css';
initShell();if(matchMedia('(max-width:760px)').matches)document.querySelector('.press-forums').open=false;document.querySelector('[data-circle-view=forum]').classList.add('is-active');const $=s=>document.querySelector(s),S={boards:[],items:[],lane:'recommended',board:'',cursor:null,serial:0,thread:null,user:null};
const campusName={all:'全校',shahe:'沙河',xueyuanlu:'学院路'};
function boards(){ $('#circle-boards').innerHTML=[{id:'',name:'全部吧',description:'看看校园里正在发生什么'},...S.boards].map((b,i)=>`<button data-board-id="${esc(b.id)}" aria-pressed="${S.board===b.id}"><span class="forum-icon" style="--forum-h:${20+i*43}">${['☷','◉','✦','⌘','↗','∑','▤'][i]||'#'}</span><span><b>${esc(b.name)}</b><small>${b.id ? `${b.posts||0} 篇帖子` : '校园里的所有讨论'}</small></span></button>`).join('');$('#post-board').innerHTML=S.boards.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');}
function card(p){const d=p.data;return `<article class="circle-post"><div class="post-author"><span class="author-avatar">${esc((p.owner?.name||'同学').slice(0,1))}</span><span><b>${esc(p.owner?.name||'同学')}</b><small>${esc(campusName[d.circle?.campus]||'全校')} · ${esc(S.boards.find(b=>b.id===d.circle?.board)?.name||'校园话题')}</small></span><span class="post-date">${esc((d.circle?.publishedAt||p.created||'').slice(0,10))}</span></div><button class="post-open" data-post="${esc(p.id)}"><h2>${esc(d.title)}</h2><p>${esc(d.body||d.summary||'')}</p></button>${p.photos?.length?`<div class="post-photos">${p.photos.slice(0,3).map(src=>`<img src="${esc(src)}" loading="lazy" alt="投稿照片">`).join('')}</div>`:''}${p.selection?`<p class="post-selection">编辑精选 · ${esc(p.selection.reason)}</p>`:''}<div class="post-footer"><button data-like="${esc(p.id)}" aria-pressed="${p.liked}">${p.liked?'♥':'♡'} ${p.likes||0}</button><button data-post="${esc(p.id)}">评论 ${p.replies||0}</button><button data-star="${esc(p.id)}">${p.starred?'★ 已收藏':'☆ 收藏'}</button></div></article>`;}
async function load(more=false){const serial=++S.serial;$('#circle-feed').setAttribute('aria-busy','true');$('#circle-status').textContent='正在加载…';try{const r=await hubApi.circleFeed({lane:S.lane,board:S.board,campus:$('#circle-campus').value,q:$('#circle-q').value.trim(),cursor:more?S.cursor:null});if(serial!==S.serial)return;S.cursor=r.nextCursor;S.items=more?[...S.items,...r.items]:r.items;$('#circle-feed').innerHTML=S.items.map(card).join('')||'<div class="product-empty"><span class="empty-symbol">✦</span><h2>第一条好讨论，从你开始。</h2><p>这里还没有公开帖子。分享一个真实经历，或发起一次合作。</p><button class="btn btn-primary" data-compose>发布第一条</button></div>';$('#circle-more').hidden=!S.cursor;if(!matchMedia('(prefers-reduced-motion:reduce)').matches)$('#circle-feed').animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:220,easing:'cubic-bezier(.2,.8,.2,1)'});$('#circle-status').textContent=S.lane==='recommended'?'根据主动选择的兴趣和编辑核对推荐，可切换“最新”。':'';}catch(e){if(serial!==S.serial)return;$('#circle-status').innerHTML=`${esc(e.message)} <button class="btn-link" data-retry>重试</button>`;}finally{if(serial===S.serial)$('#circle-feed').setAttribute('aria-busy','false');}}
async function compose(){const s=await hubState();if(!s.user){location.href=loginURL();return;}$('#circle-editor').showModal();$('#post-board').value=S.board||S.boards[0]?.id||'';$('#circle-form').elements.campus.value=$('#circle-campus').value;}
async function thread(id){const r=await hubApi.entry(id);S.thread=id;const d=r.data||{};$('#thread-body').innerHTML=`<p class="section-label">${esc(r.owner?.name||'同学')} · ${esc(campusName[d.circle?.campus]||'全校')}</p><h2>${esc(d.title)}</h2><div class="thread-text">${esc(d.body)}</div>${d.circle?.external?.url?`<a href="${esc(d.circle.external.url)}" target="_blank" rel="noopener">阅读原文 ↗</a>`:''}<h3>讨论</h3>${(r.replies||[]).map(x=>`<div class="thread-reply"><b>${esc(x.author?.name||x.owner?.name||'同学')}</b><p>${esc(x.body)}</p>${x.state!=='published'?'<small>待审核 · 仅作者与维护者可见</small>':''}</div>`).join('')||'<p class="small-note">暂无公开回复。</p>'}`;$('#reply-status').textContent='';if(!$('#circle-thread').open)$('#circle-thread').showModal();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.hasAttribute('data-board-id')){S.board=b.dataset.boardId;boards();boardDetails();await load();}if(b.hasAttribute('data-hot')){$('#circle-q').value=b.dataset.hot;S.board='';boards();boardDetails();await load();$('#circle-feed').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});}if(b.hasAttribute('data-follow-board')){const board=S.boards.find(x=>x.id===S.board);await hubApi.followBoard(board.id,!board.followed,true);board.followed=!board.followed;boardDetails();}if(b.hasAttribute('data-post'))await thread(b.dataset.post);if(b.hasAttribute('data-compose'))await compose();if(b.hasAttribute('data-retry'))await load();if(b.hasAttribute('data-like')||b.hasAttribute('data-star')){b.disabled=true;const p=S.items.find(x=>x.id===(b.dataset.like||b.dataset.star));if(b.hasAttribute('data-like')){const r=await hubApi.likeCirclePost(p.id,!p.liked);Object.assign(p,r);}else{await hubApi.star(p.id,!p.starred);p.starred=!p.starred;}$('#circle-feed').innerHTML=S.items.map(card).join('');}}catch(err){$('#circle-status').textContent=err.message;}finally{b.disabled=false;}});
$('#circle-compose').onclick=compose;$('#circle-more').onclick=()=>load(true);$('#circle-campus').onchange=()=>{load();loadTrends();};$('#circle-lanes').onchange=e=>{S.lane=e.target.value;load();};$('#circle-search').onsubmit=e=>{e.preventDefault();load();$('#circle-feed').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});};let timer;$('#circle-q').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>load(),200);};
$('#circle-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type=submit]'),v=Object.fromEntries(new FormData(f)),photos=[...f.elements.photos.files];if(photos.length>9){$('#post-status').textContent='最多上传 9 张照片。';return;}b.disabled=true;try{const uploads=[];for(const file of photos){$('#post-status').textContent=`正在上传 ${file.name}`;uploads.push((await hubApi.upload(file)).id);}const r=await hubApi.createCirclePost({title:v.title,body:v.body,tags:v.tags.split(/[，,、\s]+/).filter(Boolean).slice(0,10),uploads,rightsConfirmed:f.elements.rights.checked,circle:{format:'thread',board:v.board,campus:v.campus,visibility:'public'}});await hubApi.submit(r.id,r.editRevision);$('#post-status').innerHTML='已提交审核。<a href="me.html#entries">查看投稿进度 →</a>';f.reset();}catch(err){$('#post-status').textContent=err.message;}finally{b.disabled=false;}};
$('#thread-reply').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{const result=await hubApi.reply(S.thread,f.elements.body.value);f.reset();await thread(S.thread);$('#reply-status').textContent=result.state==='published'?'回复已发布。':'回复已提交，审核后公开。';}catch(err){$('#reply-status').textContent=err.message;}finally{b.disabled=false;}};
async function init(){const s=await hubState();S.user=s.user;const r=await hubApi.circleBoards();S.boards=r.items.map(b=>({...b,name:b.name.endsWith('吧')?b.name:`${b.name}吧`}));boards();await load();const params=new URLSearchParams(location.search);if(params.has('compose'))compose();if(params.get('post'))await thread(params.get('post'));}
loadNews();loadTrends();
init().catch(e=>{$('#circle-status').textContent=e.message;$('#circle-feed').innerHTML='<div class="product-empty"><h2>社区服务暂未连接。</h2><p>论坛需要在线账号与审核服务。已发布的项目仍可在开源广场浏览。</p><a href="discover.html">去开源广场 →</a></div>';});

function boardDetails(){const b=S.boards.find(x=>x.id===S.board),box=$('#board-info');$('#circle-feed-title').textContent=b?b.name:'大家正在聊';box.hidden=!b;if(!b)return;box.innerHTML=`<h3>${esc(b.name)}</h3><p>${esc(b.description)}</p><small>${esc(b.rules||'分享真实经历，尊重彼此；投稿审核后公开。')}</small><button data-follow-board>${b.followed?'已关注 · 点击取消':'＋ 关注这个吧'}</button>`;}
let trendSerial=0;
async function loadTrends(){const serial=++trendSerial;try{const r=await hubApi.request('circle/trends?campus='+encodeURIComponent($('#circle-campus').value));if(serial!==trendSerial)return;$('#circle-hot').innerHTML=r.items.length?r.items.map(t=>`<button data-hot="${esc(t.term)}">${esc(t.term)}<small>${t.posts} 帖</small></button>`).join(''):'<span>还没有近期热议，来分享校园见闻。</span>';$('#circle-hot').title=r.definition;}catch{if(serial!==trendSerial)return;$('#circle-hot').textContent='近期讨论暂时无法读取。';}}
async function loadNews(){try{const r=await fetch('data/featured.json',{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error();const d=await r.json(),now=Date.now();const n=d.items.find(x=>x.kind==='news'&&(!x.startsAt||Date.parse(x.startsAt)<=now)&&(!x.expiresAt||Date.parse(x.expiresAt)>now));if(!n){$('#circle-news').innerHTML='<p class="press-eyebrow">校园新闻</p><h2>下一条校园故事，等你发现。</h2><p>还没有在展示期内的编辑新闻。</p>';return;}const url=new URL(n.href||n.source?.url);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error();$('#circle-news').innerHTML=`<a href="${esc(url.href)}" target="_blank" rel="noopener"><div class="press-lead-copy"><span class="press-news-label">校园头条 · ${esc(n.source?.name||'编辑核对')}</span><h2>${esc(n.title)}</h2><p>${esc(n.dek)}</p><span class="press-news-source">${esc(n.publishedAt?.slice(0,10)||'')} · 阅读学校原报道 ↗</span></div><div class="press-date-art" aria-hidden="true"><span>CAMPUS<br>JOURNAL</span><b>${esc(n.eventAt?.slice(5).replace('-',' / ')||'NEWS')}</b><i>在矿大，记录每个值得记住的瞬间。</i></div></a>`;}catch{$('#circle-news').innerHTML='<h2>校园新闻暂时无法读取</h2><p>可以继续搜索和浏览同学的讨论。</p>';}}
