# Generated by Django 5.2.17 on 2026-10-06 03:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('size', models.PositiveIntegerField()),
                ('extension', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=300)),
                ('text', models.TextField(blank=True)),
                ('pages', models.JSONField(default=list)),
                ('extraction', models.CharField(default='pending', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCache',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('success', models.DateTimeField(null=True)),
                ('checked', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('reset', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('kind', models.CharField(default='rss', max_length=20)),
                ('entry_kind', models.CharField(default='news', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveIntegerField(default=24)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('etag', models.CharField(blank=True, max_length=300)),
                ('modified', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('campus_verified', models.BooleanField(default=False)),
                ('trusted', models.BooleanField(default=False)),
                ('github_id', models.CharField(max_length=32, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('major', models.CharField(blank=True, max_length=80)),
                ('external_links', models.JSONField(default=dict)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('digest_cursor', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=180)),
                ('detail', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('slug', models.CharField(max_length=160, unique=True)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('public_revision', models.PositiveIntegerField(default=0)),
                ('search_text', models.TextField(blank=True)),
                ('canonical_key', models.CharField(blank=True, db_index=True, max_length=500)),
                ('review_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.entry')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('key', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('evidence', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.entry')),
            ],
        ),
        migrations.CreateModel(
            name='FeedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('due', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=300)),
                ('read', models.BooleanField(default=False)),
                ('subscription', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('state', models.CharField(default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.entry')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hub.entry')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(default='默认收藏', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('beginner', models.BooleanField(default=True)),
                ('state', models.CharField(default='open', max_length=20)),
                ('evidence', models.URLField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.JSONField(default=list)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('data', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='hub_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='hub_username_ci'),
        ),
        migrations.AddConstraint(
            model_name='feedfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'repository'), name='hub_feed_feedback_unique'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='hub_notification_unique'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('entry', 'number'), name='hub_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(fields=('user', 'entry'), name='hub_star_unique'),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(fields=('user', 'entry'), name='hub_watch_unique'),
        ),
    ]
