# Generated by Django 5.2.17 on 2026-10-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='digest_cursor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='external_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='member',
            name='github_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
