# Generated by Django 5.2.17 on 2026-10-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_member_digest_cursor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
