# Generated by Django 5.2.17 on 2026-10-06 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_placeobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=80)),
                ('campus', models.CharField(max_length=20)),
                ('source_url', models.URLField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideCourse',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('faculty', models.CharField(blank=True, max_length=120)),
                ('scope', models.CharField(default='campus-catalogue', max_length=40)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('prerequisites', models.TextField(blank=True)),
                ('resources', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('faculty', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('source_url', models.URLField(max_length=1000)),
                ('photo', models.JSONField(blank=True, default=dict)),
                ('teaching', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('public_revision', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(blank=True, default=dict)),
                ('force_anonymous', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.courseoffering')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.teacher')),
            ],
            options={
                'permissions': [('trace_review_author', 'Trace anonymous review authors with audit reason')],
            },
        ),
        migrations.CreateModel(
            name='CourseReviewCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('state', models.CharField(default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.coursereview')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReviewReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('anonymous', models.BooleanField(default=True)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='hub.coursereview')),
            ],
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='hub.guidecourse'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='teachers',
            field=models.ManyToManyField(related_name='offerings', to='hub.teacher'),
        ),
        migrations.CreateModel(
            name='CourseReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hub.coursereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'user'), name='hub_course_review_like')],
            },
        ),
        migrations.CreateModel(
            name='CourseReviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.coursereview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'number'), name='hub_course_review_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('author', 'teacher'), name='hub_teacher_review_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('author', 'offering'), name='hub_offering_review_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('offering__isnull', True), ('teacher__isnull', False)), models.Q(('offering__isnull', False), ('teacher__isnull', True)), _connector='OR'), name='hub_review_single_subject'),
        ),
    ]
