# Generated by Django 5.2.17 on 2026-10-06 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_campus_clips'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBoard',
            fields=[
                ('id', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('rules', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CirclePreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('personalized', models.BooleanField(default=True)),
                ('interests', models.JSONField(default=list)),
                ('muted_creators', models.JSONField(default=list)),
                ('muted_boards', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CircleSelection',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='circle_selection', serialize=False, to='hub.entry')),
                ('revision', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.campusboard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'board'), name='hub_board_follow_unique')],
            },
        ),
        migrations.CreateModel(
            name='CircleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_feedback', to='hub.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'entry'), name='hub_circle_feedback_unique')],
            },
        ),
        migrations.CreateModel(
            name='CircleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_likes', to='hub.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'entry'), name='hub_circle_like_unique')],
            },
        ),
        migrations.CreateModel(
            name='CreatorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'creator'), name='hub_creator_follow_unique'), models.CheckConstraint(condition=models.Q(('user', models.F('creator')), _negated=True), name='hub_no_self_follow')],
            },
        ),
    ]
