# Generated by Django 5.2.17 on 2026-10-06 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_campus_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioDay',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('reserved_cny', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('codex_calls', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudioRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('brief', models.TextField(blank=True)),
                ('context_files', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudioRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=80)),
                ('prompt', models.TextField()),
                ('mode', models.CharField(default='discuss', max_length=16)),
                ('seats', models.JSONField(default=list)),
                ('rounds', models.PositiveSmallIntegerField(default=3)),
                ('state', models.CharField(default='queued', max_length=24)),
                ('claim', models.UUIDField(null=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('artifact', models.JSONField(default=dict)),
                ('approved_hash', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='hub.studioroom')),
            ],
        ),
        migrations.CreateModel(
            name='StudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('seat', models.CharField(max_length=24)),
                ('provider', models.CharField(max_length=24)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('tasks', models.JSONField(default=list)),
                ('usage', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hub.studiorun')),
            ],
        ),
        migrations.CreateModel(
            name='StudioCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(max_length=24)),
                ('reserved_cny', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('state', models.CharField(default='reserved', max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.studioday')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.studiorun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studiorun',
            constraint=models.UniqueConstraint(fields=('room', 'request_key'), name='hub_studio_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='studiomessage',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='hub_studio_message_unique'),
        ),
        migrations.AddConstraint(
            model_name='studiocall',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='hub_studio_call_unique'),
        ),
    ]
