# Generated by Django 5.2.17 on 2026-10-06 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_ai_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('campus', models.CharField(max_length=20)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('remind_at', models.DateTimeField()),
                ('preference', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(default='scheduled', max_length=24)),
                ('reminded', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'remind_at'], name='seat_plan_due')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'request_key'), name='seat_plan_request_unique')],
            },
        ),
    ]
