# Generated by Django 5.2.17 on 2026-10-06 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_seat_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository', models.CharField(db_index=True, max_length=140)),
                ('tag', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('license', models.CharField(max_length=60)),
                ('source_url', models.URLField(max_length=600)),
                ('release_url', models.URLField(blank=True, max_length=600)),
                ('published', models.DateTimeField(null=True)),
                ('path', models.CharField(max_length=200)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'tag', 'name'), name='hub_mirror_asset_unique')],
            },
        ),
    ]
