# Generated by Django 5.2.17 on 2026-10-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_mirror_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='hub_device_sync_unique')],
            },
        ),
    ]
