# Generated by Django 5.2.17 on 2026-10-07 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_faculty_sources(apps, schema_editor):
    """教师资料机器人：按 campus/faculty-sources.json 给每个学院建一条定时来源（kind=faculty），迁移后 worker 自动按周运行。"""
    import json
    from pathlib import Path
    config = Path(__file__).resolve().parents[2] / 'faculty-sources.json'
    if not config.exists():
        return
    data = json.loads(config.read_text(encoding='utf-8'))
    Source = apps.get_model('hub', 'Source')
    for item in data.get('colleges', []):
        Source.objects.update_or_create(url=item['start'], defaults={
            'name': item['college'], 'kind': 'faculty', 'entry_kind': 'faculty',
            'enabled': True, 'interval_hours': data.get('intervalHours', 168)})


def drop_faculty_sources(apps, schema_editor):
    apps.get_model('hub', 'Source').objects.filter(kind='faculty').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_mirror_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ExternalMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=300)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='hub.guidecourse')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='hub.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'url'), name='hub_mention_teacher_url'), models.UniqueConstraint(fields=('course', 'url'), name='hub_mention_course_url'), models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('teacher__isnull', False)), models.Q(('course__isnull', False), ('teacher__isnull', True)), _connector='OR'), name='hub_mention_single_subject')],
            },
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hub.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reply', 'user'), name='hub_reply_like_unique')],
            },
        ),
        migrations.RunPython(seed_faculty_sources, drop_faculty_sources),
    ]
