# Generated by Django 5.2.17 on 2026-10-07 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_reputation_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeikuangTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=240, unique=True)),
                ('target', models.CharField(max_length=240)),
                ('title', models.CharField(max_length=240)),
                ('link', models.CharField(blank=True, max_length=600)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('checks', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('decided_by', models.CharField(blank=True, max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('decided', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeikuangMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=12)),
                ('kind', models.CharField(default='chat', max_length=16)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('state', models.CharField(default='sent', max_length=12)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beikuang_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
