# Generated by Django 5.2.17 on 2026-10-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_beikuang'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.CharField(max_length=64)),
                ('day', models.DateField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.entry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'viewer', 'day'), name='hub_entry_view_unique')],
            },
        ),
    ]
