# Generated by Django 5.2.17 on 2026-10-07 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_source_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('course', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(default='未分类', max_length=80)),
                ('state', models.CharField(db_index=True, default='queued', max_length=24)),
                ('source_kind', models.CharField(max_length=16)),
                ('source_document_id', models.CharField(blank=True, max_length=160)),
                ('source_meta', models.JSONField(default=dict)),
                ('selected_pages', models.JSONField(default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_pages', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('review', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shelved', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.upload')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hub.questionpaper')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('paper', 'number'), name='hub_question_revision_unique')],
            },
        ),
    ]
