# Generated by Django 5.2.17 on 2026-10-09 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_studiomessage_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=16)),
                ('origin', models.CharField(max_length=240, unique=True)),
                ('goal', models.TextField()),
                ('state', models.CharField(default='queued', max_length=16)),
                ('progress', models.CharField(blank=True, max_length=600)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialOverride',
            fields=[
                ('key', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hub.editorialoverride')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('override', 'number'), name='hub_editorial_revision_unique')],
            },
        ),
    ]
